# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-01-23 10:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Crowd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crowd_funding', models.CharField(blank=True, max_length=70)),
                ('crowd_progress', models.CharField(blank=True, max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin_from', models.CharField(blank=True, choices=[('01', '亲朋介绍'), ('02', '网络'), ('03', '电视广告'), ('04', '其他途径')], max_length=70)),
                ('describe', models.TextField(blank=True)),
                ('doctor_type', models.CharField(blank=True, choices=[('01', '中'), ('02', '西')], max_length=70)),
                ('doctor_address', models.CharField(blank=True, max_length=100)),
                ('disease_type', models.CharField(blank=True, max_length=70)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('praise', models.IntegerField(blank=True, default=0)),
                ('crowd', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='medicine.Crowd')),
            ],
            options={
                'ordering': ['-created_time'],
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_outline', models.CharField(blank=True, max_length=100)),
                ('task_deadline', models.CharField(blank=True, max_length=70)),
                ('task_start_time', models.DateTimeField(auto_now_add=True)),
                ('task_state', models.CharField(blank=True, choices=[('01', '待执行'), ('02', '执行中'), ('03', '执行完成'), ('04', '失效')], max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='TaskProgress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('des', models.CharField(blank=True, default='执行任务记录描述', max_length=70)),
                ('path', models.FileField(blank=True, upload_to='image/')),
                ('task_progress_time', models.DateTimeField(auto_now_add=True)),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='medicine.Task')),
            ],
        ),
        migrations.CreateModel(
            name='Top',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_top', models.BooleanField(default=False)),
                ('top_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=70)),
                ('telephone', models.CharField(blank=True, max_length=70)),
                ('age', models.IntegerField(blank=True, default=20)),
                ('address', models.CharField(blank=True, max_length=70)),
            ],
        ),
        migrations.AddField(
            model_name='task',
            name='task_executors',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='medicine.User'),
        ),
        migrations.AddField(
            model_name='subject',
            name='followers',
            field=models.ManyToManyField(blank=True, related_name='_subject_followers_+', to='medicine.User'),
        ),
        migrations.AddField(
            model_name='subject',
            name='initiator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='u+', to='medicine.User'),
        ),
        migrations.AddField(
            model_name='subject',
            name='task',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='medicine.Task'),
        ),
        migrations.AddField(
            model_name='subject',
            name='top',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='medicine.Top'),
        ),
        migrations.AddField(
            model_name='crowd',
            name='crowd_providers',
            field=models.ManyToManyField(blank=True, to='medicine.User'),
        ),
    ]
