# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-01-20 10:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='type',
            field=models.CharField(blank=True, choices=[('01', '中医'), ('02', '西医')], max_length=70),
        ),
    ]
