# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-01-27 08:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0003_auto_20180127_1528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_state',
            field=models.CharField(blank=True, choices=[('01', '待执行'), ('02', '执行中'), ('03', '执行完成'), ('04', '失效')], default='01', max_length=70),
        ),
    ]
