# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-01-29 09:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0004_auto_20180127_1600'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='taskprogress',
            options={'ordering': ['-created_time']},
        ),
        migrations.AddField(
            model_name='taskprogress',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
