# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-01-30 02:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0005_auto_20180129_1758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskprogress',
            name='des',
            field=models.TextField(blank=True, default='执行任务记录描述'),
        ),
    ]
