# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-02-01 10:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0006_auto_20180130_1025'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='title',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
