# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-02-03 05:40
from __future__ import unicode_literals

from django.db import migrations, models
import medicine.models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0007_subject_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileBean',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('des', models.TextField(blank=True, default='文件描述')),
                ('post_time', models.DateTimeField(auto_now_add=True)),
                ('path', models.FileField(blank=True, upload_to=medicine.models.user_directory_path)),
            ],
            options={
                'ordering': ['-post_time'],
            },
        ),
    ]
