# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-02-03 09:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0012_subject_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='content',
            field=models.TextField(blank=True),
        ),
    ]
